"""QAIRT (QNN SDK) helpers: raw tensor I/O for qnn-net-run and a build-script template.

The script is a template for QAIRT 2.47 (the paper's SDK): tool names and options must be checked
against the SDK documentation of the installed version before use.
"""

import json
from pathlib import Path

import numpy as np


def write_raw_input(features: np.ndarray, path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.ascontiguousarray(features, dtype=np.float32).tofile(path)
    return path


def read_raw_output(result_dir, index: int, shape, output_name: str = "head.logits") -> np.ndarray:
    """Read Result_<index>/<output>.raw written by qnn-net-run (tries the sanitized tensor name too)."""
    folder = Path(result_dir) / f"Result_{index}"
    for name in (output_name, output_name.replace(".", "_")):
        path = folder / f"{name}.raw"
        if path.exists():
            return np.fromfile(path, dtype=np.float32).reshape(shape)
    raise FileNotFoundError(f"no output {output_name!r} in {folder}")


def htp_config(graph_names: list[str], dsp_arch: str = "v73", soc_model: int | None = None) -> dict:
    device = {"dsp_arch": dsp_arch}
    if soc_model is not None:
        device["soc_model"] = soc_model
    return {
        "graphs": [{"graph_names": graph_names, "vtcm_mb": 0, "O": 3}],
        "devices": [device],
        "context": {"weight_sharing_enabled": True},
    }


def build_script(buckets: list[str], encodings: str = "encodings.json", out_dir: str = "qnn", host: str = "x86_64-linux-clang") -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by iparakeet.deploy.qnn: template for QAIRT 2.47; verify tools/options against its docs.",
        "set -euo pipefail",
        ': "${QNN_SDK_ROOT:?set QNN_SDK_ROOT to the QAIRT install}"',
        f"mkdir -p {out_dir}",
    ]
    for b in buckets:
        lines += [
            f"qnn-onnx-converter --input_network {b}.onnx --output_path {out_dir}/{b}.cpp \\",
            f"    --quantization_overrides {encodings} --input_list calib/{b}/input_list.txt \\",
            "    --act_bitwidth 8 --weights_bitwidth 8 --bias_bitwidth 32 --use_per_channel_quantization",
            f"qnn-model-lib-generator -c {out_dir}/{b}.cpp -b {out_dir}/{b}.bin -o {out_dir}/lib -t {host}",
        ]
    libs = ",".join(f"{out_dir}/lib/{host}/lib{b}.so" for b in buckets)
    lines += [
        "# one context holding every bucket graph with shared weights (HTP weight sharing)",
        f'qnn-context-binary-generator --backend "$QNN_SDK_ROOT/lib/{host}/libQnnHtp.so" \\',
        f"    --model {libs} \\",
        f"    --config_file htp_backend_ext.json --binary_file iparakeet_ctx --output_dir {out_dir}",
        "# on the device (adb): qnn-net-run --backend libQnnHtp.so --retrieve_context iparakeet_ctx.bin \\",
        "#     --input_list <bucket>/input_list.txt --output_dir outputs/<bucket> --profiling_level basic",
    ]
    return "\n".join(lines) + "\n"


def write_htp_configs(out_dir, graph_names: list[str], dsp_arch: str = "v73") -> None:
    out = Path(out_dir)
    (out / "htp_config.json").write_text(json.dumps(htp_config(graph_names, dsp_arch), indent=2))
    ext = {"backend_extensions": {"shared_library_path": "libQnnHtpNetRunExtensions.so", "config_file_path": "htp_config.json"}}
    (out / "htp_backend_ext.json").write_text(json.dumps(ext, indent=2))
